-- DROP DATABASE
DROP DATABASE IF EXISTS coolback_db;

-- CREATE DATABASE
CREATE DATABASE coolback_db;

CREATE TABLE Category (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
category_name VARCHAR(50) NOT NULL
)

CREATE TABLE Product (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
product_name VARCHAR(50) NOT NULL,
price DECIMAL(10, 2) CHECK (price > 0),
stock INT NOT NULL DEFAULT 10,
category_id INT NOT NULL FOREIGN KEY REFERENCES Category(id)
)

CREATE TABLE Tag (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
tag_name VARCHAR(50)
)

CREATE TABLE ProductTag (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
product_id INT FOREIGN KEY REFERENCES Product(id),
tag_id INT FOREIGN KEY REFERENCES Tag(id)
)


